#--------------------------------------------------------------------------------
# Values for this class - EDIT THIS SECTION.
#--------------------------------------------------------------------------------
workshop_repo   : "https://github.com/cbgoodman/uno-spa-quant-ii"
workshop_site   : "http://cbgoodman.github.io/uno-spa-quant-ii"

#--------------------------------------------------------------------------------
# owner
#--------------------------------------------------------------------------------
name: SPA Quant II
username: cbgoodman
#--------------------------------------------------------------------------------
# Standard Software Carpentry settings - should not need to be modified.
#--------------------------------------------------------------------------------
contact           : "cbgoodman@unomaha.edu"
quant_github      : "http://github.com/cbgoodman/uno-spa-quant-ii"
quant_githubio    : "http://cbgoodman.github.io/uno-spa-quant-ii"
quant_twitter     : "http://twitter.com/cbgoodman"

#--------------------------------------------------------------------------------
# markdown language
#--------------------------------------------------------------------------------
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighting: rouge

highlighter: rouge
