#--------------------------------------------------------------------------------
# Values for this class - EDIT THIS SECTION.
#--------------------------------------------------------------------------------
workshop_repo   : "https://github.com/cbgoodman/uno-spa-quant-ii"
workshop_site   : "http://cbgoodman.github.io/uno-spa-quant-ii"

#--------------------------------------------------------------------------------
# Standard Software Carpentry settings - should not need to be modified.
#--------------------------------------------------------------------------------
contact           : "cbgoodman@unomaha.edu"
quant_site        : "http://spa.unomaha.edu"
quant_github      : "https://github.com/cbgoodman/uno-spa-quant-ii"
quant_githubio    : "https://cbgoodman.github.io/uno-spa-quant-ii"
quant_twitter     : "http://twitter.com/cbgoodman"

#--------------------------------------------------------------------------------
# markdown language
#--------------------------------------------------------------------------------
markdown        : kramdown
kramdown        :
  entity_output : as_input # &mdash; is output as &mdash;
  smart_quotes  : [39, 39, 34, 34] # decimal for left/right single/double quotes
exclude         : [tools]
