name: SPA Quant II

username: cbgoodman
repo: uno-spa-quant-ii

encoding:     "utf-8"

markdown:    kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
syntax_highlighter: rouge
